name = "EzWAV"
uuid = "56f67a90-58ed-51bd-970b-daa95479f66b"
authors = ["tatssuki <tatsuki0824@hotmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
